### ISSUE TITLE
build on ubuntu 16.04

### ISSUE THREAD

**Issue by zablah** [redBorder/bpctl#1]
i tried to get bypass driver for my PEG2BPI5 card and after a lot of search i found your code.
ubuntu 16.04 has kernel version 4.4.98
and as i found that linux kernel remove silicom driver from version > 3.12
so i add silicom module to my kernel 4.4.97 and i install my new kernel but i can't  find the bpctl binary file
after installing this code and try to build it first i get this error:

> Makefile:166: *** *** Aborting the build. *** This driver is not supported on kernel versions older than 2.4.0.  Stop.

i edit Makefile and add my kernel version code to:

> KVER_CODE := "263265" 

then i rebuild the code and i get another error:

```
make
gcc  -c bp_util.c -DBP_DBI_FLAG -DPMC_FIX_FLAG -DVER_STR_SET="\"5.0.40.29-rb\""
gcc bp_util.o -o bpctl_util
make -C /lib/modules/4.4.97.silicom/build SUBDIRS=/home/jo/pypy/bpctl modules
make[1]: Entering directory '/home/jo/linux-4.4.97'
  CC [M]  /home/jo/pypy/bpctl/bp_mod.o
/home/jo/pypy/bpctl/bp_mod.c: In function ‘proc_getdir’:
/home/jo/pypy/bpctl/bp_mod.c:6955:17: error: dereferencing pointer to incomplete type ‘struct proc_dir_entry’
     for (pde=pde->subdir; pde; pde = pde->next) {
                 ^
/home/jo/pypy/bpctl/bp_mod.c: At top level:
/home/jo/pypy/bpctl/bp_mod.c:7000:29: error: unknown type name ‘write_proc_t’
                             write_proc_t *write_proc,
                             ^
/home/jo/pypy/bpctl/bp_mod.c:7001:29: error: unknown type name ‘read_proc_t’
                             read_proc_t *read_proc,
                             ^
/home/jo/pypy/bpctl/bp_mod.c: In function ‘bypass_proc_create_dev_sd’:
/home/jo/pypy/bpctl/bp_mod.c:8128:9: error: implicit declaration of function ‘bypass_proc_create_entry_sd’ [-Werror=implicit-function-declaration]
     if (bypass_proc_create_entry_sd(&(current_pfs->bypass_info),
         ^
cc1: some warnings being treated as errors
scripts/Makefile.build:258: recipe for target '/home/jo/pypy/bpctl/bp_mod.o' failed
make[2]: *** [/home/jo/pypy/bpctl/bp_mod.o] Error 1
Makefile:1405: recipe for target '_module_/home/jo/pypy/bpctl' failed
make[1]: *** [_module_/home/jo/pypy/bpctl] Error 2
make[1]: Leaving directory '/home/jo/linux-4.4.97'
Makefile:219: recipe for target 'default' failed
make: *** [default] Error 2
```
so what can i do to get the driver ?
please help

**Comment by azunite** [comment]
i get same error , any one fixed?

**Comment by azunite** [comment]
I have solved this problem by download new version control util from silicom; 
this is my spec nic : https://www.silicom-usa.com/drivercat/bypass-2/?pname=PEG4BPI
